### ISSUE TITLE
Install from git?

### ISSUE THREAD

**Issue by pschmitt** [aphecetche/asdf-tmux#3]
Is there any way to make ASDF use the current git HEAD as the version to install?

**Comment by aphecetche** [comment]
Generally speaking for ASDF I must confess I don't know what's the expected behaviour,  but for asdf-tmux specifically the answer is no, as the [list-all](https://github.com/aphecetche/asdf-tmux/blob/df00852eed34be24bbc172a746c9ce5e7e018e97/bin/list-all#L13) script explicitly selects tags only.
