### ISSUE TITLE
Issue with versions `3.3` or higher on MacOS

### ISSUE THREAD

**Issue by awseward** [aphecetche/asdf-tmux#5]
Hi, there. Thanks much for making this an asdf plugin; I find it super helpful!

#### The Issue

I found an issue when trying to install version `3.3-rc` on MacOS. It looks like it's caused by a change in 3.3 [here](https://github.com/tmux/tmux/blob/1bf2f811ea8835dd24bdb773b5be4df517767d1f/CHANGES#L35-L36): 

>* Do not configure on macOS without the user making a choice about utf8proc
> (either --enable-utf8proc or --disable-utf8proc).

Without specifying either of those options, `./configure` fails like so:
```
checking platform... darwin
configure:
configure:         macOS library support for Unicode is very poor,
configure:         particularly for complex codepoints like emojis;
configure:         to use these correctly, configuring with
configure:         --enable-utf8proc is recommended. To build
configure:         without anyway, use --disable-utf8proc
configure:
configure: error: must give --enable-utf8proc or --disable-utf8proc
make: *** No targets specified and no makefile found.  Stop.
```
Here's the calling line:
https://github.com/aphecetche/asdf-tmux/blob/df00852eed34be24bbc172a746c9ce5e7e018e97/bin/install#L32

#### Workaround

In order to fix for myself I made the following change locally:
```diff
# ~/.asdf/plugins/tmux/bin/install:32
- ./configure …
+ ./configure --enable-utf8proc …
```

#### Proper Fix

The script could just specify `--enable-utf8proc` (this is the option that tmux's error recommends); however, a user would be out of luck if they really wanted `--disable…` instead.

To provide for that use case, it might make sense to use the same approach as another plugin, [`asdf-postgres`](https://github.com/smashedtoatoms/asdf-postgres#asdf-options), implemented [here](https://github.com/smashedtoatoms/asdf-postgres/blob/701737320a8aaa0a0e3c8608513f3154ae90260e/bin/install#L64-L78). Essentially, users on MacOS would be able to configure via a file like this:

```sh
# ~/.asdf-tmux-configure-options
TMUX_EXTRA_CONFIGURE_OPTIONS='--enable-utf8proc'
```

---

Let me know what you think, and if you'd like, I'm happy to submit a PR with whatever changes make the most sense.

**Comment by aphecetche** [comment]
@awseward to be honest I no longer use `asdf` myself. But I'm happy to accept PRs, or, even better, to pass on this repo to someone who does and who cares ;-)

**Comment by awseward** [comment]
Hey @aphecetche! Sorry for the delayed response; I haven't had a chance to get back to the computer in a bit.

Unfortunately I can't commit to taking on the repo itself, but I can at least offer https://github.com/aphecetche/asdf-tmux/pull/6 for what it's worth.

**Comment by aphecetche** [comment]
@awseward I've merged your PR. thanks.
